name: metrics_gaearon
on:
  # schedule:
  # run at 0, 8 every day
  # run two times per day
  # - cron: "0 0 * * *"
  # - cron: "0 8 * * *"
  # - cron: "0 16 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-actions-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{secrets.METRICS_TOKEN}}
          # Options
          filename: metrics_gaearon.svg
          user: gaearon
          base: header, activity, repositories, metadata
          base_indepth: yes
          config_timezone: Canada/Eastern
          config_twemoji: yes
          config_order: base.header, base.activity+community, base.repositories, isocalendar, achievements, languages
          # plugin_languages_analysis_timeout: 15
          # plugin_languages_categories: markup, programming
          # plugin_languages_colors: github
          # plugin_languages_details: bytes-size, percentage
          # plugin_languages_limit: 8
          # plugin_languages_recent_categories: markup, programming
          # plugin_languages_recent_days: 14
          # plugin_languages_recent_load: 300
          # plugin_languages_sections: most-used
          # plugin_languages_threshold: 2%
          # plugin_lines: yes
          # plugin_notable: yes
          # plugin_notable_filter: stars:>100
          # plugin_notable_from: organization
          # plugin_notable_indepth: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # repositories_skipped:
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 30
          use_prebuilt_image: yes
